apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crawler

resources:
  - k8s/mongo.yaml
  - k8s/namespace.yaml
  - k8s/nimbus.yaml
  - k8s/secrets.yaml
  - k8s/storm-ui.yaml
  - k8s/supervisor.yaml
  - k8s/urlfrontier.yaml
  - k8s/zookeeper.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: storm-crawler
    includeSelectors: false

images:
  - name: inaccurate-article-crawler
    newTag: "1.0"